platform: linux

image_resource:
  type: docker-image
  source:
    repository: Bankmonitor/spring-boot
    tag: latest-war

inputs:
- name: osusume-java-spring

run:
  path: ./osusume-java-spring/ci/test.sh
